web/router.ex
defmodule JiraDashboard.Router do
  use JiraDashboard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", JiraDashboard do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/dashboard", DashboardController, :index
    resources "/tasks", TaskController
  end

  # Other scopes may use custom stacks.
  # scope "/api", JiraDashboard do
  #   pipe_through :api
  # end
end

lib/jira_dashboard_frontend/endpoint.ex
defmodule JiraDashboard.Endpoint do
  use Phoenix.Endpoint, otp_app: :jira_dashboard

  socket "/socket", JiraDashboard.UserSocket
  socket "/jira", JiraDashboard.ActivitySocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :jira_dashboard, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_jira_dashboard_key",
    signing_salt: "rFRpyJ4j"

  plug JiraDashboard.Router
end

lib/jira_dashboard_frontend/repo.ex
defmodule JiraDashboard.Repo do
  use Ecto.Repo, otp_app: :jira_dashboard
end

web/models/task.ex
defmodule JiraDashboard.Task do
  use JiraDashboard.Web, :model

  schema "tasks" do
    field :title, :string
    field :description, :string
    field :weight, :integer
    field :position, :integer
    field :status, :string

    timestamps
  end

  @required_fields ~w(title description weight position status)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/task_query.ex
defmodule JiraDashboard.TaskQuery do
  import Ecto.Query

  def grouped do
    [
      JiraDashboard.TaskQuery.active,
      JiraDashboard.TaskQuery.in_progress,
      JiraDashboard.TaskQuery.done
    ]
  end

  def active do
    query = from tasks in JiraDashboard.Task,
            where: tasks.status == "Active",
            select: tasks
    JiraDashboard.Repo.all query
  end

  def in_progress do
    query = from tasks in JiraDashboard.Task,
            where: tasks.status == "In Progress",
            select: tasks
    JiraDashboard.Repo.all query
  end

  def done do
    query = from tasks in JiraDashboard.Task,
            where: tasks.status == "Done",
            select: tasks
    JiraDashboard.Repo.all query
  end
end

web/controllers/dashboard_controller.ex
defmodule JiraDashboard.DashboardController do
  use JiraDashboard.Web, :controller

  alias JiraDashboard.Dashboard
  alias JiraDashboard.TaskQuery

  def index(conn, _params) do
    grouped_tasks = JiraDashboard.TaskQuery.grouped
    render(conn, "index.html", grouped_tasks: grouped_tasks)
  end
end

web/controllers/page_controller.ex
defmodule JiraDashboard.PageController do
  use JiraDashboard.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/task_controller.ex
defmodule JiraDashboard.TaskController do
  use JiraDashboard.Web, :controller

  alias JiraDashboard.Task

  plug :scrub_params, "task" when action in [:create, :update]

  def index(conn, _params) do
    tasks = Repo.all(Task)
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Task.changeset(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    changeset = Task.changeset(%Task{}, task_params)

    case Repo.insert(changeset) do
      {:ok, _task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Repo.get!(Task, id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Repo.get!(Task, id)
    changeset = Task.changeset(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Repo.get!(Task, id)
    changeset = Task.changeset(task, task_params)

    case Repo.update(changeset) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Repo.get!(Task, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end
end

web/views/dashboard_view.ex
defmodule JiraDashboard.DashboardView do
  use JiraDashboard.Web, :view
end

web/views/error_view.ex
defmodule JiraDashboard.ErrorView do
  use JiraDashboard.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule JiraDashboard.LayoutView do
  use JiraDashboard.Web, :view
end

web/views/page_view.ex
defmodule JiraDashboard.PageView do
  use JiraDashboard.Web, :view
end

web/views/task_view.ex
defmodule JiraDashboard.TaskView do
  use JiraDashboard.Web, :view
end

web/templates/dashboard/index.html.eex
<div class="row">
  <div class="col-md-9">
    <%= for group <- @grouped_tasks do %>
      <div class="col-sm-6 col-md-4">
        <h1><%= hd(group).status %></h1>
        <%= for task <- group do %>
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3><%= task.title %></h3>
            </div>
            <div class="panel-body">
              <p><%= task.description %></p>
              <p><b><%= task.weight %></b></p>
            </div>
            <div class="panel-footer">
              <%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %>
              <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %>
              <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs pull-right" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="list-group"></div>
    </div>
  </div>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="wrapper" role="main">
      <div class="header">
        <div class="container-fluid">
          <h1 class="navbar-brand pull-left">
            <span>
              <img src="/images/phoenix.png" width="75%">
            </span>
          </h1>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link "DASHBOARD", to: dashboard_path(@conn, :index) %></li>
              <li><%= link "TASKS", to: task_path(@conn, :index) %></li>
            </ul>
          </div>
        </div>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="container-fluid">
        <div class="main-content">
          <div class="main-head">
            <%= @inner %>
          </div>
        </div>
      </div>

    </div>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="//timeago.yarp.com/jquery.timeago.js"></script>
    <script type="text/javascript" src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/task/edit.html.eex
<h2>Edit task</h2>

<%= render "form.html", changeset: @changeset,
                        action: task_path(@conn, :update, @task) %>

<%= link "Back", to: task_path(@conn, :index) %>

web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, "Title", class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :description, "Description", class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :weight, "Weight", class: "control-label" %>
    <%= number_input f, :weight, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :position, "Position", class: "control-label" %>
    <%= number_input f, :position, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :status, "Status", class: "control-label" %>
    <%= text_input f, :status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/task/index.html.eex
<h2>Listing tasks</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Weight</th>
      <th>Position</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.weight %></td>
      <td><%= task.position %></td>
      <td><%= task.status %></td>

      <td class="text-right">
        <%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New task", to: task_path(@conn, :new) %>

web/templates/task/new.html.eex
<h2>New task</h2>

<%= render "form.html", changeset: @changeset,
                        action: task_path(@conn, :create) %>

<%= link "Back", to: task_path(@conn, :index) %>

web/templates/task/show.html.eex
<h2>Show task</h2>

<ul>
  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>
  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>
  <li>
    <strong>Weight:</strong>
    <%= @task.weight %>
  </li>
  <li>
    <strong>Position:</strong>
    <%= @task.position %>
  </li>
  <li>
    <strong>Status:</strong>
    <%= @task.status %>
  </li>
</ul>

<%= link "Edit", to: task_path(@conn, :edit, @task) %>
<%= link "Back", to: task_path(@conn, :index) %>